name: flutter_fit_utils_ui
description: "A flutter package that offers pre-built UI components to build your UI faster. This package is part of the flutter_fit_utils environement."
version: 1.2.6
homepage: https://pub.dev/packages/flutter_fit_utils_ui
repository: https://github.com/s0punk/flutter_fit_utils_ui
issue_tracker: https://github.com/s0punk/flutter_fit_utils_ui/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - ui
  - components

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fit_utils: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
